### ISSUE TITLE
Error in conversion of 'IsolationForest::iForest' objects to PMML

### ISSUE THREAD

**Issue by jaroslav-kuchar** [jpmml/r2pmml#10]
I was not able to properly use a conversion of 'IsolationForest::iForest' objects to PMML.
For the following code:
```R
library("IsolationForest")
library("r2pmml")
data("iris")
iForest <- IsolationForest::IsolationTrees(iris)
r2pmml(iForest, "iForest.pmml")
```
I got errors:
```
SEVERE: Failed to convert
java.lang.IllegalArgumentException
	at org.jpmml.rexp.IForestConverter.encodeFeatures(IForestConverter.java:71)
	at org.jpmml.rexp.ModelConverter.encodePMML(ModelConverter.java:78)
	at org.jpmml.rexp.ModelConverter.encodePMML(ModelConverter.java:74)
	at org.jpmml.rexp.Main.run(Main.java:149)
	at org.jpmml.rexp.Main.main(Main.java:97)

Exception in thread "main" java.lang.IllegalArgumentException
	at org.jpmml.rexp.IForestConverter.encodeFeatures(IForestConverter.java:71)
	at org.jpmml.rexp.ModelConverter.encodePMML(ModelConverter.java:78)
	at org.jpmml.rexp.ModelConverter.encodePMML(ModelConverter.java:74)
	at org.jpmml.rexp.Main.run(Main.java:149)
	at org.jpmml.rexp.Main.main(Main.java:97)
Error in .convert(tempfile, file, ...) : 1
```
Java 1.8
R 3.3.0

**Comment by vruusmann** [comment]
The `IsolationForest` algorithm doesn't support categorical (ie. R's `factor` data type) variables. If you want to train an isolation forest model for the Iris dataset, then you can use only the first four columns:
```R
data(iris)
iris_vars = iris[, -ncol(iris)]

iForest = IsolationForest::IsolationForest(iForest)
```

Admittedly, the above `IllegalArgumentException` should provide an appropriate message.

**Comment by vruusmann** [comment]
Also, this is the R script that is used for generating JPMML-R integration tests:
https://github.com/jpmml/jpmml-r/blob/master/src/test/R/IsolationForest.R

**Comment by jaroslav-kuchar** [comment]
Thanks for your prompt reply. I did not know about the issues with categorical variables. It works!
