### ISSUE TITLE
convert ARIMA to PMML

### ISSUE THREAD

**Issue by vkarthi46** [jpmml/r2pmml#7]
is there a standard way to export a time series in R? r2pmml would work,but when i try to use the library , perhaps incorrectly ,i get an error..

For Example, My code look like below..

library(forecast)

library("devtools")
library(RCurl)
library(httr)
set_config( config( ssl_verifypeer = 0L ) )
install_github(repo = "jpmml/r2pmml",force = TRUE)
library("r2pmml")

model=auto.arima(ts.data)
r2pmml(model, "ets.pmml")

and the srror i get this..

Apr 17, 2016 7:10:57 PM org.jpmml.rexp.Main run
INFO: Parsing RDS..
Apr 17, 2016 7:10:57 PM org.jpmml.rexp.Main run
INFO: Parsed RDS in 0 ms.
Apr 17, 2016 7:10:57 PM org.jpmml.rexp.Main run
INFO: Initializing default Converter
Exception in thread "main" java.lang.IllegalArgumentException
        at org.jpmml.rexp.ConverterFactory.newConverter(ConverterFactory.java:46)
        at org.jpmml.rexp.Main.run(Main.java:134)
        at org.jpmml.rexp.Main.main(Main.java:97)
Error in .convert(tempfile, file, ...) : 1
In addition: Warning message:
running command '"java" -cp "C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/guava-19.0.jar;C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/istack-commons-runtime-2.21.jar;C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/jaxb-core-2.2.11.jar;C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/jaxb-runtime-2.2.11.jar;C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/jcommander-1.48.jar;C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/jpmml-converter-1.0.3.jar;C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/jpmml-r-1.1.4.jar;C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/jpmml-xgboost-1.0.2.jar;C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/pmml-agent-1.2.11.jar;C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/pmml-model-1.2.11.jar;C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/pmml-model-metro-1.2.11.jar;C:/Users/vkarth2/Documents/R/R-3.2.4/library/r2pmml/java/pmml-schema-1.2.11.jar;C:/Users/vka [... truncated]

**Comment by vruusmann** [comment]
The list of supported R model types is given in the README file of the JPMML-R project: https://github.com/jpmml/jpmml-r/blob/master/README.md

As one can see, the `forecast::Arima` model type is not listed there at the moment.

The support for ARIMA models should become possible once PMML 4.3 is released. You can track the status of the relevant feature request in DMG issue tracker (requires signup): http://mantis.dmg.org/view.php?id=8

**Comment by ssriganesh** [comment]
@vruusmann ,Just wanted the check if the r2pmml supports the Arima with 4.3.
